name: RemoteQuery
main: com.github.CubieX.RemoteQuery.RemoteQuery
author: CubieX
softdepend: [PermissionsEx, zPermissions, bPermissions, PermissionsBukkit]
version: 0.0.2
description: Query remote DB via HTTP by calling a PHP script

commands:
    rq:
      description: Using RemoteQuery
      usage: /rq version | reload | query

permissions:
    remotequery.use:
        description: Use normal commands
        default: op
    remotequery.admin:
        description: Allows use of all commands and effects
        default: op
        children:
          remotequery.use: true